[tool.poetry]
name = "ml-service"
version = "0.1.0"
description = ""
authors = ["alexei <rojd75@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.51"
fastapi = "^0.140.0"
joblib = "^1.5.3"
scikit-learn = "^1.9.0"
email-validator = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
